services:
  grafana:
    image: grafana/grafana-oss:11.1.0
    container_name: grafana-splunk-dev
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/var/lib/grafana/plugins/firestoned-splunk-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
      # Allow our unsigned plugin to load in dev. Remove this once you sign
      # the plugin via `npm run sign`.
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=firestoned-splunk-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
